import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

import { ThemeProvider } from "./theme/theme-provider";
import Navbar from "@/Components/Navbar";
import SearchWrapper from "@/Components/SearchWrapper";
import Header from "@/Components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IMDb Clone",
  description: "Generated by Kamalakar",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
        <Providers>
          <Header />
          <Navbar/>
          <SearchWrapper/>
          {children}
        </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}

